---

common:
  k8s_namespace: cert-manager

  app_name: cert-manager
  image_version: v0.7.0

  issuers:
    letsencrypt:
      name: letsencrypt-staging
      email: user@example.com
      server: https://acme-staging-v02.api.letsencrypt.org/directory # Staging
      # server: https://acme-v02.api.letsencrypt.org/directory # Production
      challengeMechanism:
        type: http
      privateKeySecretRef:
        name: example-issuer-account-key


  templates:
    # For 000_crds.yaml - see README.md
    # - template: 000_crds.yaml
    - template: 001_namespace.yaml.j2
    - template: CAinjector/001_serviceAccount.yaml.j2
    - template: CAinjector/005_RBAC.yaml.j2
    - template: CAinjector/020_deployment.yaml.j2
    - template: certManager/001_serviceAccount.yaml.j2
    - template: certManager/005_RBAC.yaml.j2
    - template: certManager/020_deployment.yaml.j2
    - template: webhook/001_serviceAccount.yaml.j2
    - template: webhook/005_RBAC.yaml.j2
    - template: webhook/010_service.yaml.j2
    - template: webhook/020_deployment.yaml.j2
    # ERROR:k8s_handle:RuntimeError: Unknown kinds
    # - template: webhook/030_apiService.yaml.j2
    # - template: webhook/040_ValidatingWebhookConfiguration.yaml.j2

# For deploy Cert-Manager
main:
  app_name: cert-manager


# Deploy issuers
staging_issuer:

  issuers:
    letsencrypt:
      name: letsencrypt-staging
      email: mail@gmail.com
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: letsencrypt-staging-account-key
      challengeMechanism:
        type: dns
        dns:
          name: eu-central-1-zones
          region: eu-central-1
          accessKeyID: MyAmazonOpenKey
          hostedZoneID: MyAmazonZoneID
          secretAccessKeySecretRef:
            name: letsencrypt-route53-credentials
            data: "{{ env='ROUTE53_STAGING_SECRET_KEY' }}"

  templates:
    # ERROR:k8s_handle:RuntimeError: Unknown kind "ClusterIssuer" in generated file
    - template: ClusterIssuers/letsencrypt.yaml.j2


http_issuer:

  issuers:
    letsencrypt:
      name: letsencrypt-http-staging
      email: mail@gmail.com
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: letsencrypt-http-staging-account-key
      challengeMechanism:
        type: http

  templates:
    # ERROR:k8s_handle:RuntimeError: Unknown kind "ClusterIssuer" in generated file
    - template: ClusterIssuers/letsencrypt.yaml.j2
